[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
]

[tool.setuptools]
py-modules = ["ANN", "ga", "Example_GA_ANN"]
